<?php

//state key
const LEFTBRACE = 1;
const COLON = 2;
const COMMA = 3;
const RIGHTBRACE = 4;
const LEFTBRACKET = 5;
const RIGHTBRACKET = 6;
const DOUBLEQUOTE = 7;
const SWDEFAULT = 8;
const BACKSLASH = 9;

const DONE = "task_done";
const STOREKEY = "store_key";
const MAKEKEY = "make_key";
const MAKEVALUE = "make_value";
const EMPTYY = "";
const KEYVALSTORED = "key_val_stored";
const STOREKEYVAL = "store_key_value";


const ZERO = 0;
const HEADER = "header";
const DATA = "data";
const ENTRY = "entry";
const CREATEDATAOBJ = "create_data_object";
const NEEDSWORK = "needs work ";
const STOREUNITS = "store_units";
const IGNORE = "ignore_label";
const GETNEXTCHAR = 0;
const CREATEENTRY = "create_entry_object";
const MAKE_ENTRY_KEY = "make_entry_key";
const CONTINUEPROCESSING = 1;
const MAKELABEL = "make_label";
const MAKELABELVALUE = "make_label_value";
const MAKEDESCRIPTIONVALUE = "make_description_value";
const MAKENEWDATAOBJECT = "make_new_data_object";
const MAKETAXONOMYKEY = "make_taxo_key";
const TESTKEY = "test_key";

//labels
const FACTS = "facts";
const XBRLLABEL = "dei";
const DATALABEL = 'label';
const DESCRIPLABEL = 'description';
const SEC_ID = "cik";
const COMPANY_NAME = "entityName";
const DOC_ENTITY_TYPE = "dei";
const US_GAAP_TYPE = "us-gaap";
const INVEST_TYPE = "invest";
const IFRS_TYPE = "ifrs";
const IFRS_FULL_TYPE = "ifrs-full";
const SRT_TYPE = "srt";						//would be good for taxonomy class to update this file with new ones TODO
const UNITS = "units";						//and update RecordBuilder switch statement too :-)
const COUNTRY = "countries";
const CURRENCY = "currencies";


const  NEWTERM = "new term";
const ADDEDTODB = " added to db\n";


